### ISSUE TITLE
Need user object to be retrievable either with token or in separate api call.

### ISSUE THREAD

**Issue by fivetwelve** [toitoi-co/toitoi-admin#13]
If a user refreshes the -cms page, they are still technically logged into -admin but will need to re-retrieve firebase auth token and user.site data that contains domain and firebase bucket key. Post-login, only the auth token is retrievable from /generate-token call.

**Comment by joepie91** [comment]
Should be two routes:

* __GET:__ For retrieving the current user object.
* __PUT:__ For modifying the current user object (eg. change profile settings).
