### ISSUE TITLE
Endpoints required to update user's site params

### ISSUE THREAD

**Issue by fivetwelve** [toitoi-co/toitoi-admin#20]
During onboard flow, endpoints are required for user to save their site (subdomainName), and plan selection (planId), and possibly theme (see issue #21).

**Comment by joepie91** [comment]
I'll create `/site` routes for this, with an API similar to the `/profile` routes.

**Comment by joepie91** [comment]
`planId` won't be set directly from the CMS, as this should be dependent on the user completing the billing process. Currently it will allow for creating a site and modifying its name, and the theme attribute will be added later.

**Comment by fivetwelve** [comment]
Will need some input from @pudly on how to handle plan selection because it was apparently the second onboarding step: https://toitoi.slack.com/archives/general/p1460217490000689 (and c.f. [the photo link](https://goo.gl/photos/hrG6mgA2G2C19E8Z8)  in the subsequent reply)

**Comment by pudly** [comment]
Plan and billing are not necessarily linked, since there could be free plans. Also billing should be handled primarily in the CMS, even if it does leverage stripe. The setting needs to be applied both in -admin and in the stripe integration.

We can discuss on slack if that doesn't make sense
