### ISSUE TITLE
/admin prefix?

### ISSUE THREAD

**Issue by joepie91** [toitoi-co/toitoi-admin#7]
Need to consider whether to move routes like `/users` to an `/admin` path prefix, given that the API is gaining an increasing amount of (non-admin) responsibilities. This would prevent collisions between admin-privileged operations and user-privileged operations.

**Comment by fivetwelve** [comment]
At the moment, I'm not sure how much it affects the FE layer since I only need to call /login and /generate-token. It's trivial for me to update this API call if there is a change involved so I am fine with either way.
